name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-20.04, ubuntu-22.04, centos-7, centos-8, arch-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Build
      run: make
    
    - name: Test
      run: make test

  package:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make debhelper rpm build-essential fakeroot
        # Add other package-specific dependencies as needed

    - name: Build packages
      run: |
        make deb
        make rpm
        # Add other package formats