name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-20.04, ubuntu-22.04, centos-7, centos-8, arch-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y make
      
    - name: Build
      run: make
    
    - name: Test
      run: make test

  package-deb:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Debian package using Docker
      uses: docker://debian:bullseye
      with:
        args: sh -c "apt-get update && apt-get install -y make debhelper devscripts && make deb"
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: packaging/deb/*.deb

  package-rpm:
    runs-on: centos-8
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build RPM package
      run: |
        sudo yum install -y make rpm-build
        make rpm
    
    - name: Upload RPM package
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: packaging/rpm/*.rpm

  package-arch:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Arch Linux package using Docker
      uses: docker://archlinux:latest
      with:
        args: sh -c "pacman -Sy --noconfirm make binutils fakeroot && make arch"
    
    - name: Upload Arch Linux package
      uses: actions/upload-artifact@v4
      with:
        name: arch-package
        path: packaging/arch/*.pkg.tar.*