name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-20.04, ubuntu-22.04]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y make
      
    - name: Build
      run: make
    
    - name: Test
      run: make test

  package-deb:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Debian package using Docker
      uses: docker://debian:bullseye
      env:
        DEBEMAIL: safarikikandi@gmail.com
        DEBFULLNAME: NetSnmp Enterprise
      with:
        args: sh -c "apt-get update && apt-get install -y make debhelper devscripts && make deb"
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: packaging/deb/*.deb

  package-source-deb:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Fix changelog format
      run: |
        cd packaging/deb/debian
        # Replace $(date -R) with actual date
        sed -i 's/\$(date -R)/Tue, 01 Jan 2024 12:00:00 +0000/' changelog
        # Ensure proper changelog format
        if ! grep -q "urgency=" changelog; then
          echo "Fixing changelog format..."
          # Add proper changelog header if missing
          sed -i '1i\netsnmp-enterprise (2.0.0-1) stable; urgency=medium\n\n  * Build triggered via GitHub Actions\n' changelog
        fi
    
    - name: Build Debian source package using Docker
      uses: docker://debian:bullseye
      env:
        DEBEMAIL: safarikikandi@gmail.com
        DEBFULLNAME: NetSnmp Enterprise
      with:
        args: |
          sh -c "
          apt-get update && 
          apt-get install -y make debhelper devscripts && 
          cd /github/workspace/packaging/deb && 
          # Build source package
          debuild -S -us -uc
          # Copy results to a known location
          mkdir -p /github/workspace/source-packages && 
          cp ../*.dsc ../*.tar.* ../*_source.changes /github/workspace/source-packages/
          "
    
    - name: Upload Debian source package
      uses: actions/upload-artifact@v4
      with:
        name: deb-source-package
        path: source-packages/*
  # package-rpm:
  #   runs-on: centos-8
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
    
  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Build RPM package
  #     run: |
  #       sudo yum install -y make rpm-build
  #       make rpm
    
  #   - name: Upload RPM package
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: rpm-package
  #       path: packaging/rpm/*.rpm

  # package-arch:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
    
  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Build Arch Linux package using Docker
  #     uses: docker://archlinux:latest
  #     with:
  #       args: sh -c "pacman -Sy --noconfirm make binutils fakeroot && make arch"
    
  #   - name: Upload Arch Linux package
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: arch-package
  #       path: packaging/arch/*.pkg.tar.*