name: Release and PPA Deployment

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '2.0.0'
      build_type:
        description: 'Build type'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - binary-only
          - source-only
      deploy_ppa:
        description: 'Deploy to PPA?'
        required: true
        default: false
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      run_id: ${{ steps.set-outputs.outputs.run_id }}
      artifact_name: ${{ steps.set-outputs.outputs.artifact_name }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set outputs
      id: set-outputs
      run: |
        echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT
        echo "artifact_name=build-artifacts-${{ github.run_id }}" >> $GITHUB_OUTPUT
    
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${{ github.event.inputs.version || '2.0.0' }}" >> $GITHUB_OUTPUT
          echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Build binary packages using Docker
      if: github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'binary-only' || github.event_name == 'release'
      uses: docker://debian:bullseye
      env:
        DEBEMAIL: safarikikandi@gmail.com
        DEBFULLNAME: NetSnmp Enterprise
      with:
        args: >
          sh -c "
          apt-get update && 
          apt-get install -y make debhelper devscripts &&
          make deb
          "
        
    - name: Build source package using Docker
      if: github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'source-only' || github.event.inputs.deploy_ppa == 'true'
      uses: docker://debian:bullseye
      env:
        DEBEMAIL: safarikikandi@gmail.com
        DEBFULLNAME: NetSnmp Enterprise
        VERSION: ${{ steps.version.outputs.VERSION }}
      with:
        args: |
          sh -c "
          apt-get update
          apt-get install -y make debhelper devscripts
          # Create orig tarball from root
          cd /github/workspace
          tar czf ../netsnmp-enterprise_${VERSION}.orig.tar.gz --exclude=./packaging/deb --exclude=./.git .
          # Build package
          cd packaging/deb
          dch -v '${VERSION}-1' 'Build triggered via NetSnmp Enterprise'
          dch -r --distribution stable ''
          debuild -S -sa
          "
        
    - name: Create GitHub Release (only for actual releases)
      if: steps.version.outputs.IS_RELEASE == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          packaging/deb/*.deb
        generate_release_notes: true
        tag_name: ${{ github.event.release.tag_name }}
        
    - name: Upload artifacts for manual builds and PPA
      if: steps.version.outputs.IS_RELEASE == 'false' || github.event.inputs.deploy_ppa == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set-outputs.outputs.artifact_name }}
        path: |
          packaging/deb/*.deb
          ../*.dsc
          ../*.tar.*
          ../*_source.changes
          ../*.orig.tar.gz
        retention-days: 1

  deploy-ppa:
    runs-on: ubuntu-latest
    needs: build-and-release
    if: |
      (github.event_name == 'release' && github.event.release.prerelease == false) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_ppa == 'true')
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-and-release.outputs.artifact_name }}
        path: ./
        
    - name: Install dput and setup GPG
      run: |
        sudo apt-get update && sudo apt-get install -y dput devscripts
        
    - name: List downloaded files
      run: ls -la
      
    - name: Check for source packages
      id: check-files
      run: |
        if ls *.changes 1> /dev/null 2>&1; then
          echo "changes_files_exist=true" >> $GITHUB_OUTPUT
        else
          echo "changes_files_exist=false" >> $GITHUB_OUTPUT
          echo "No .changes files found"
        fi
        
    - name: Deploy to PPA
      if: steps.check-files.outputs.changes_files_exist == 'true'
      env:
        PPA_URL: ${{ secrets.PPA_URL }}
        PPA_GPG_KEY: ${{ secrets.PPA_GPG_KEY }}
        PPA_GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
        DEBEMAIL: safarikikandi@gmail.com
        DEBFULLNAME: NetSnmp Enterprise
      run: |
        echo "Deploying to PPA: $PPA_URL"
        
        if [ -n "$PPA_GPG_KEY" ]; then
          # Import GPG key
          echo "$PPA_GPG_KEY" | gpg --import --batch --yes
          
          # Get key ID
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2 | head -1)
          echo "Using GPG key ID: $KEY_ID"
          
          # Sign each changes file
          for changes_file in *.changes; do
            echo "Signing $changes_file"
            debsign -k "$KEY_ID" "$changes_file"
          done
        else
          echo "No GPG key provided, skipping signing"
        fi
        
        # Upload to PPA
        for changes_file in *.changes; do
          echo "Uploading $changes_file to PPA"
          dput "$PPA_URL" "$changes_file"
        done
        
    - name: Skip PPA deployment if no files
      if: steps.check-files.outputs.changes_files_exist == 'false'
      run: |
        echo "No source packages found, skipping PPA deployment"
        echo "Available files:"
        ls -la