name: Sign Packages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  sign-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Build packages
      run: |
        make clean
        make
        make deb
        make rpm

    - name: Sign Debian packages
      run: |
        chmod +x scripts/gpg-setup.sh
        for deb_file in packaging/deb/*.deb; do
          ./scripts/gpg-setup.sh sign-deb "$deb_file"
        done

    - name: Sign RPM packages
      run: |
        for rpm_file in packaging/rpm/*.rpm; do
          ./scripts/gpg-setup.sh sign-rpm "$rpm_file"
        done

    - name: Upload signed packages
      uses: actions/upload-artifact@v3
      with:
        name: signed-packages
        path: |
          packaging/deb/*.deb
          packaging/deb/*.asc
          packaging/rpm/*.rpm

    - name: Update release with signed packages
      uses: softprops/action-gh-release@v1
      with:
        files: |
          packaging/deb/*.deb
          packaging/deb/*.asc
          packaging/rpm/*.rpm
        tag_name: ${{ github.ref }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}